version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: baza
      POSTGRES_USER: nbd
      POSTGRES_PASSWORD: nbdpassword
    ports:
      - 5432:5432
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
  payara:
    image: payara/server-full:5.2022.3-jdk17
    ports:
          - 4848:4848
          - 8080:8080
          - 8181:8181
    volumes:
      - ./tmp/payara:/tmp/data
